### ISSUE TITLE
[0.8.1] Crash on startup.

### ISSUE THREAD

**Issue by vicenterusso** [wavetermdev/waveterm#807]
**Describe the bug**
Crash on starup. When I run, it shows up for like 3 seconds and it crashes.

**To Reproduce**
Just instaled RPM and ran Appimage version, both broken.

**Desktop (please complete the following information):**
 - OS: Fedora 40

**Additional context**
Also tried verison 0.8.0, it does not crashes but auto updates, next time I run its already 0.8.1 it crashes the same way

Log:

```
  ~/Desktop ❯ ./waveterm-linux-x86_64-0.8.1.appimage                                                                                                             took  31s at  08:24:45
Checking for update
Update for version 0.8.1 is not available (latest version: 0.8.1, downgrade is allowed).
[313114:0924/083516.762876:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[313114:0924/083517.767228:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Uncaught Exception: Error: connect ECONNREFUSED 127.0.0.1:38077
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 38077
}
Stack Trace: Error: connect ECONNREFUSED 127.0.0.1:38077
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
```

**Comment by bagustris** [comment]
A similar error also happens on Ubuntu 24.04, which is installed using the DEB version. Please take a look at the messages below.

```bash
[17293:0924/222238.066196:ERROR:mime_util_xdg.cc(137)] Invalid mime.cache file does not contain null prior to ALIAS_LIST_OFFSET=44
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: deb
Checking for update
Update for version 0.8.1 is not available (latest version: 0.8.1, downgrade is allowed).
Uncaught Exception: Error: connect ECONNREFUSED 127.0.0.1:43691
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16) {
  errno: -111,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 43691
}
Stack Trace: Error: connect ECONNREFUSED 127.0.0.1:43691
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
```

**Comment by esimkowitz** [comment]
Could you please send the full contents of ~/.waveterm/waveapp.log to support@waveterm.dev? We've gotten multiple reports of this but we haven't been able to reproduce it on any of our machines. Do you have any special firewall settings on your machine that could impact localhost?

**Comment by esimkowitz** [comment]
Ah I got it to repro! Looks like the backend is crashing when sending telemetry, will look into it further

**Comment by esimkowitz** [comment]
Update: Looks like it's an issue with us statically linking glibc when using netcgo. I'm removing the static linking flag and building a new beta build, will send when it's published.

**Comment by esimkowitz** [comment]
Alright let me know if this release works for you: https://github.com/wavetermdev/waveterm/releases/tag/v0.8.2-beta.0

I've tested it on my machine and it appears to fix it

**Comment by bagustris** [comment]
@esimkowitz  in Ubuntu 20.04, different machine from 0.8.1 with 24.04, the beta version even didn't start, perhaps, due to glibc version. I installed the amd64 DEB version. Log is attached below: 

```
2024-09-25 09:19:18 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 09:19:18 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 09:19:18 spawned wavesrv
2024-09-25 09:19:18 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:18 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:18 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:18 wavesrv exited, shutting down
2024-09-25 09:19:26 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 09:19:26 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 09:19:26 spawned wavesrv
2024-09-25 09:19:26 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:26 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:26 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:26 wavesrv exited, shutting down
2024-09-25 09:20:13 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 09:20:13 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 09:20:13 spawned wavesrv
2024-09-25 09:20:13 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:20:13 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:20:13 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:20:13 wavesrv exited, shutting down
```

**Comment by esimkowitz** [comment]
@bagustris try downloading the latest release and let me know if that fixes it for you

**Comment by bagustris** [comment]
@esimkowitz I downloaded the latest DEB version: waveterm-linux-amd64-0.8.2.deb. It didn't start on 20.04. Log is below:

```
2024-09-25 09:19:18 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 09:19:18 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 09:19:18 spawned wavesrv
2024-09-25 09:19:18 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:18 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:18 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:18 wavesrv exited, shutting down
2024-09-25 09:19:26 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 09:19:26 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 09:19:26 spawned wavesrv
2024-09-25 09:19:26 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:26 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:26 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:19:26 wavesrv exited, shutting down
2024-09-25 09:20:13 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 09:20:13 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 09:20:13 spawned wavesrv
2024-09-25 09:20:13 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:20:13 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:20:13 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 09:20:13 wavesrv exited, shutting down
2024-09-25 10:39:45 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 10:39:45 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 10:39:45 spawned wavesrv
2024-09-25 10:39:45 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:39:45 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:39:45 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:39:45 wavesrv exited, shutting down
2024-09-25 10:42:41 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 10:42:41 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 10:42:41 spawned wavesrv
2024-09-25 10:42:41 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:42:41 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:42:41 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:42:41 wavesrv exited, shutting down
2024-09-25 10:47:00 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 10:47:00 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 10:47:00 spawned wavesrv
2024-09-25 10:47:01 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:47:01 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:47:01 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 10:47:01 wavesrv exited, shutting down
```

**Comment by esimkowitz** [comment]
@bagustris can you email the contents of ~/.waveterm/waveapp.log to support@waveterm.dev? I'd like to inspect the backend logs to see if it's the same issue from the previous build.

**Comment by esimkowitz** [comment]
@bagustris thank you so much for your assistance and patience, I've got a new build for you to try, can you see if this one works for you? https://github.com/wavetermdev/waveterm/releases/tag/v0.8.3-beta.3

**Comment by bagustris** [comment]
@esimkowitz still the same error hapens. The reason is the glibc version installed in 20.04 is version 2.31.

```
2024-09-25 13:19:25 waveterm-app starting, WAVETERM_HOME=/home/bagus/.waveterm, electronpath=/opt/Wave/resources/app.asar/dist gopath=/opt/Wave/resources/app.asar.unpacked/dist arch=linux/x64
2024-09-25 13:19:25 trying to run local server /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64
2024-09-25 13:19:25 spawned wavesrv
2024-09-25 13:19:25 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 13:19:25 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 13:19:25 /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/Wave/resources/app.asar.unpacked/dist/bin/wavesrv.x64)
2024-09-25 13:19:25 wavesrv exited, shutting down
```
GLIB version
```
bagus@m049:~$ ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

Maybe it works in newer Ubuntu (24.04?)

**Comment by esimkowitz** [comment]
Hmm... okay so to confirm this is with the 0.8.3-beta.3 release that you are still seeing the glibc issue?

**Comment by bagustris** [comment]
Yes, that is with the newest 0.8.3-beta.deb, amd64 version.

**Comment by esimkowitz** [comment]
Got it, gonna see if I can manually target an older glibc version that hopefully will be a lowest-common-denominator

**Comment by esimkowitz** [comment]
Haha okay let's try this again: https://github.com/wavetermdev/waveterm/releases/tag/v0.8.3-beta.9

**Comment by bagustris** [comment]
@esimkowitz both versions 0.8.3-beta.9 and beta.10 works on Ubuntu 20.04.
(it would be helpful to have arg `--version` to check the version)

**Comment by esimkowitz** [comment]
Ah good idea, can you make a separate issue to add `--version`?

**Comment by esimkowitz** [comment]
Closing as resolved as of 0.8.3

**Comment by Prane-B** [comment]
This issue is still there on 0.8.3 for me

`[praneshb@archlinux Downloads]$ waveterm
Checking for beta autoupdate feature for deb/rpm distributions
Found package-type: rpm
Checking for update
Update for version 0.8.3 is not available (latest version: 0.8.3, downgrade is allowed).
[5593:0925/160018.257069:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[5593:0925/160019.702232:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[5593:0925/160022.049241:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
`
I am getting that from the terminal when I run wave and then it crashes

**Comment by esimkowitz** [comment]
@Prane-B Can you open a new issue? This seems like a GPU hardware compatibility issue based on the error.

**Comment by vicenterusso** [comment]
I can confirm the new version is not crashing on startup
