### ISSUE TITLE
Fix Wave Terminal Icon for Linux

### ISSUE THREAD

**Issue by sawka** [wavetermdev/waveterm#97]
No Icon is showing up for Linux users in the dock.

It looks like we need a different icon format for Linux / Windows builds:
https://stackoverflow.com/questions/31529772/how-to-set-app-icon-for-electron-atom-shell-app

Right now we're just setting the icon in "icns" format (which only seems to work for MacOS).

**Comment by nathanv** [comment]
Better docs here: https://www.electronforge.io/guides/create-and-add-icons#linux

**Comment by sawka** [comment]
This should be fixed with v0.5.1

**Comment by nathanv** [comment]
I am still having issues. I upgrade to 0.5.1 but the dot files are from 0.5.0 . Is there anything I need to do to fix?
